version: '3.9' # Compose file format version
services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017" # Expose MongoDB port on the host

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    depends_on:
      - mongodb # Ensures mongo-express starts after mongodb
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb # Use the service name to communicate
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    ports:
      - "8081:8081" # Expose Mongo Express on port 8081

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379" # Expose Redis port on the host
